### ISSUE TITLE
Not enough values to unpack

### ISSUE THREAD

**Issue by Rainismer** [showlab/computer_use_ootb#9] opened 2024-10-26 12:48 UTC
**When I enter the command and send it I get the following error:**
     
![2ED8E1B393D55E0C4A61B8933A656887](https://github.com/user-attachments/assets/e64aa793-8bea-4c04-83a3-0ada1edc550f)

Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\gradio\queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\gradio\blocks.py", line 2018, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\gradio\blocks.py", line 1579, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\gradio\utils.py", line 691, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\gradio\utils.py", line 685, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\gradio\utils.py", line 668, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\computeruse\Lib\site-packages\gradio\utils.py", line 829, in gen_wrapper
    response = next(iterator)
               ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\computer_use_ootb\app.py", line 179, in process_input
    for message in sampling_loop(state):
  File "C:\Users\Administrator\Desktop\computer_use_ootb\app.py", line 203, in sampling_loop
    for message in accumulate_messages(
  File "C:\Users\Administrator\Desktop\computer_use_ootb\app.py", line 189, in accumulate_messages
    for message in sampling_loop_sync(*args, **kwargs):
  File "C:\Users\Administrator\Desktop\computer_use_ootb\computer_use_demo\loop.py", line 184, in sampling_loop_sync
    ComputerTool(),
    ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\computer_use_ootb\computer_use_demo\tools\computer.py", line 96, in __init__
    self.width, self.height = self.get_screen_size()
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\computer_use_ootb\computer_use_demo\tools\computer.py", line 256, in get_screen_size
    width, height = map(int, lines[0].split())
    ^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by mhmtemnacr** [comment] 2024-10-27 22:56
I'm getting the same error

**Comment by h-siyuan** [comment] 2024-10-28 07:29
The issue is fixed in our latest update. Thank you @Rainismer for providing details in the discussion group to help us fix the issue!

To all users: 
You can join our discussion group to get real-time resonses from our team :)

**Comment by h-siyuan** [comment] 2024-10-28 07:30
Issue fixed, this issue will be closed.

**Closed by h-siyuan** 2024-10-28 07:30 UTC
